### ISSUE TITLE
Use w3id for a permanent namespace URI for the ontology

### ISSUE THREAD

**Issue by clange** [WDAqua/QAOntology#2]
See https://w3id.org/ for how it works.

**Comment by D063520** [comment]
Done, here is the permanent URI:
https://w3id.org/wdaqua/qanary

**Comment by clange** [comment]
Great! However, it redirects to a GitHub page rather than to the ontology's implementation, i.e. #3 is not satisfied. I'll comment in #3. Once #3 is fixed properly, please change the w3id redirect.

**Comment by clange** [comment]
Please forget about my re-opening; you did exactly the right thing :-)
