### ISSUE TITLE
Publish LOD version of the ontology as RDF/XML

### ISSUE THREAD

**Issue by clange** [WDAqua/QAOntology#8]
RDF/XML is ugly but it's the common denominator. When requesting `application/rdf+xml` content from https://w3id.org/wdaqua/qanary# I expect to get RDF/XML, and when seeing a file with an `*.owl` extension (which is what you see when you go to https://w3id.org/wdaqua/qanary# with an HTML client), I also expect RDF/XML.

FYI: the current syntax of the ontology implementation is called "OWL XML" and commonly uses the filename extension `*.owx`.

**Comment by D063520** [comment]
???? I do not get it. So when you do:

curl -H "Accept: application/rdf+xml" https://w3id.org/wdaqua/qanary# 

you get:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>303 See Other</title>
</head><body>

<h1>See Other</h1>

<p>The answer to your request is located <a href="https://raw.githubusercontent.com/WDAqua/QAOntology/master/qanary.owl">here</a>.</p>

<hr>

<address>Apache/2.4.7 (Ubuntu) Server at w3id.org Port 443</address>
</body></html>

and 

https://raw.githubusercontent.com/WDAqua/QAOntology/master/qanary.owl

is in rdf/xml ugly format. So what is wrong? The extension?

**Comment by D063520** [comment]
Ahhhhh, I got it, I sayed that the default document is ttl and not owl. I will change that. Then hopefully LOD will not complain!

**Comment by D063520** [comment]
No it is not working. Any suggestions .....

**Comment by D063520** [comment]
Now I got was the request was. Changed

**Comment by clange** [comment]
Thanks! BTW depending on how much effort we want to put into our w3id redirect, we can offer the ontology in further content types. After `application/rdf+xml`, `text/turtle` would be the next obvious one. But, in principle, we could also offer `application/owl+xml`, which is this OWL XML you had used first. But as `application/rdf+xml` is universally understood, these have a low priority.
